# CodeRabbit configuration aligned with AGENTS.md and local CI pipeline

reviews:
  # Overall review tone & automation behavior
  style: chill
  auto_review:
    enabled: true
    on_draft: false
    on_update: true

  # Focus review scope on source, tests, and scripts; skip generated/auxiliary dirs
  scope:
    include:
      - "insanely_fast_whisper_rocm/**"
      - "tests/**"
      - "scripts/**"
    exclude:
      - ".venv/**"
      - ".ruff_cache/**"
      - ".pytest_cache/**"
      - "benchmarks/**"
      - "uploads/**"
      - "temp_uploads/**"
      - "transcripts/**"
      - "transcripts-srt/**"
      - "transcripts-txt/**"

  # Expectations derived from AGENTS.md (Ruff + Pytest + SOLID)
  expectations:
    ruff_rules: true
    pep8_surface: true
    naming_conventions: true
    import_style: true
    docstrings:
      enabled: true
      style: google
      require_for_public_api: true
    modernization:
      prefer_fstrings: true
      prefer_pep585_generics: true
    tests:
      require_tests_for_new_code: true
      require_tests_for_bugfixes: true
      min_coverage: 0.85
    solid_principles:
      srp_single_responsibility: true
      ocp_open_closed: true
      lsp_substitutability: true
      isp_small_interfaces: true
      dip_dependency_inversion: true
    configuration_management:
      forbid_direct_env_access_outside_constants: true

  # Tool integrations – keep Ruff primary, others supportive
  tools:
    ruff:
      enabled: true
    markdownlint:
      enabled: true
    hadolint:
      enabled: true
    yamllint:
      enabled: true
    shellcheck:
      enabled: true
    pylint:
      enabled: false
    flake8:
      enabled: false

  # Single source of truth for code quality: scripts/local-ci.sh
  pre_merge_checks:
    local_ci:
      enabled: true
      description: "Run the full local CI pipeline (fix, format, tests, coverage)."
      commands:
        - "./scripts/local-ci.sh"

  # What PR feedback should emphasize
  focus:
    - "Ruff violations (F, E, W, N, D, DOC, TID, UP, FA)."
    - "Missing or incorrect Google-style docstrings on public APIs."
    - "Violations of naming/import rules described in AGENTS.md."
    - "Missing tests for new behavior or bug fixes; low-coverage risk areas."
    - "Design issues conflicting with SOLID checklist in AGENTS.md."
    - "Direct env access (os.environ / os.getenv) outside <package>.utils.constant."

chat:
  enabled: true
  style: chill
