services:
  insanely-fast-whisper-rocm-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev

    image: ghrc.io/beecave-homelab/insanely-fast-whisper-rocm:dev
    # image: beecave/insanely-fast-whisper-rocm:dev
    container_name: insanely-fast-whisper-rocm-dev
    restart: unless-stopped

    # To allow AMD GPU access:
    devices:
      - "/dev/kfd:/dev/kfd"
      - "/dev/dri:/dev/dri"
    stdin_open: true
    tty: true
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp=unconfined
    group_add:
      - video
    ipc: host
    shm_size: 8G

    env_file:
      - .env

    ports:
      - "8888:8888"  # API port
      - "7861:7861"  # WebUI port
    
    volumes:
      - "./transcripts:/app/transcripts"
      - "./temp_uploads:/app/temp_uploads"
      - "./insanely_fast_whisper_api:/app/insanely_fast_whisper_api"
      - "./tests:/app/tests"
      - "$HOME/.cache/huggingface/hub:/root/.cache/huggingface/hub"

    #################################################
    ## Default: Gradio WebUI without debug logging ##
    #################################################
    command: ["python", "-m", "insanely_fast_whisper_api.webui.cli"]
    
    ##############################################
    ## Alternative commands (uncomment to use): ##
    ##############################################
    #
    # Gradio WebUI with debug logging:
    # command: ["python", "-m", "insanely_fast_whisper_api.webui.cli",  "--debug"]
    #
    # API only:
    # command: ["python", "-m", "insanely_fast_whisper_api"]
    #
    # API with verbose output:
    # command: ["python", "-m", "insanely_fast_whisper_api", "-v"]
    #
    # Custom WebUI with extra args:
    # command: ["python", "-m", "insanely_fast_whisper_api.webui.cli", "--port", "7860", "--host", "0.0.0.0", "--debug"]
    #
    # CLI transcription example:
    # command: ["python", "-m", "insanely_fast_whisper_api.cli.cli", "transcribe", "tests/file.mp3", "--debug"]
