"""
This type stub file was generated by pyright.
"""

from typing import Any, TypedDict
from typing_extensions import NotRequired

class FileData(TypedDict):
    name: str | None
    data: str | None
    size: NotRequired[int | None]
    is_file: NotRequired[bool]
    orig_name: NotRequired[str]
    mime_type: NotRequired[str]
    is_stream: NotRequired[bool]
    ...


class ParameterInfo(TypedDict):
    label: str
    parameter_name: str
    parameter_has_default: NotRequired[bool]
    parameter_default: NotRequired[Any]
    type: dict
    python_type: dict
    component: str
    example_input: Any
    ...


