"""
This type stub file was generated by pyright.
"""

from collections.abc import Callable

"""Contains methods that generate documentation for Gradio functions and classes."""
classes_to_document = ...
classes_inherit_documentation = ...
def set_documentation_group(m): # -> None:
    """A no-op for backwards compatibility of custom components published prior to 4.16.0"""
    ...

def extract_instance_attr_doc(cls, attr): # -> str:
    ...

_module_prefixes = ...
def document(*fns, inherit=..., documentation_group=...): # -> Callable[..., Any]:
    """
    Defines the @document decorator which adds classes or functions to the Gradio
    documentation at www.gradio.app/docs.

    Usage examples:
    - Put @document() above a class to document the class and its constructor.
    - Put @document("fn1", "fn2") above a class to also document methods fn1 and fn2.
    - Put @document("*fn3") with an asterisk above a class to document the instance attribute methods f3.
    """
    ...

def document_fn(fn: Callable, cls) -> tuple[str, list[dict], dict, str | None]:
    """
    Generates documentation for any function.
    Parameters:
        fn: Function to document
    Returns:
        description: General description of fn
        parameters: A list of dicts for each parameter, storing data for the parameter name, annotation and doc
        return: A dict storing data for the returned annotation and doc
        example: Code for an example use of the fn
    """
    ...

def document_cls(cls): # -> tuple[Literal[''], dict[Any, Any], Literal['']] | tuple[LiteralString, dict[Any, Any], str | None]:
    ...

def generate_documentation(): # -> dict[Any, Any]:
    ...

