"""
This type stub file was generated by pyright.
"""

import asyncio
import concurrent.futures
import time
import httpx
from collections.abc import Callable, Coroutine
from dataclasses import dataclass
from datetime import datetime
from enum import Enum
from pathlib import Path
from threading import Lock
from typing import Any, Literal, NewType, TYPE_CHECKING, TypedDict
from gradio_client.data_classes import ParameterInfo

if TYPE_CHECKING:
    ...
API_URL = ...
SSE_URL_V0 = ...
SSE_DATA_URL_V0 = ...
SSE_URL = ...
SSE_DATA_URL = ...
WS_URL = ...
UPLOAD_URL = ...
LOGIN_URL = ...
CONFIG_URL = ...
API_INFO_URL = ...
RAW_API_INFO_URL = ...
SPACE_FETCHER_URL = ...
RESET_URL = ...
SPACE_URL = ...
HEARTBEAT_URL = ...
CANCEL_URL = ...
STATE_COMPONENT = ...
INVALID_RUNTIME = ...
class Message(TypedDict, total=False):
    msg: str
    output: dict[str, Any]
    event_id: str
    rank: int
    rank_eta: float
    queue_size: int
    success: bool
    progress_data: list[dict]
    log: str
    level: str
    ...


def get_package_version() -> str:
    ...

__version__ = ...
class TooManyRequestsError(Exception):
    """Raised when the API returns a 429 status code."""
    ...


class QueueError(Exception):
    """Raised when the queue is full or there is an issue adding a job to the queue."""
    ...


class InvalidAPIEndpointError(Exception):
    """Raised when the API endpoint is invalid."""
    ...


class SpaceDuplicationError(Exception):
    """Raised when something goes wrong with a Space Duplication."""
    ...


class ServerMessage(str, Enum):
    send_hash = ...
    queue_full = ...
    estimation = ...
    send_data = ...
    process_starts = ...
    process_generating = ...
    process_completed = ...
    log = ...
    progress = ...
    heartbeat = ...
    server_stopped = ...
    unexpected_error = ...
    close_stream = ...
    process_streaming = ...


class Status(Enum):
    """Status codes presented to client users."""
    STARTING = ...
    JOINING_QUEUE = ...
    QUEUE_FULL = ...
    IN_QUEUE = ...
    SENDING_DATA = ...
    PROCESSING = ...
    ITERATING = ...
    PROGRESS = ...
    FINISHED = ...
    CANCELLED = ...
    LOG = ...
    @staticmethod
    def ordering(status: Status) -> int:
        """Order of messages. Helpful for testing."""
        ...
    
    def __lt__(self, other: Status) -> bool:
        ...
    
    @staticmethod
    def msg_to_status(msg: str) -> Status:
        """Map the raw message from the backend to the status code presented to users."""
        ...
    


@dataclass
class ProgressUnit:
    index: int | None
    length: int | None
    unit: str | None
    progress: float | None
    desc: str | None
    @classmethod
    def from_msg(cls, data: list[dict]) -> list[ProgressUnit]:
        ...
    


@dataclass
class StatusUpdate:
    """Update message sent from the worker thread to the Job on the main thread."""
    code: Status
    rank: int | None
    queue_size: int | None
    eta: float | None
    success: bool | None
    time: datetime | None
    progress_data: list[ProgressUnit] | None
    log: tuple[str, str] | None = ...
    type: Literal["status", "output"] = ...


@dataclass
class OutputUpdate:
    """Update message sent from the worker thread to the Job on the main thread."""
    outputs: list[Any]
    success: bool
    type: Literal["output"] = ...
    final: bool = ...


Update = NewType("Update", StatusUpdate | OutputUpdate)
def create_initial_status_update(): # -> StatusUpdate:
    ...

@dataclass
class JobStatus:
    """The job status.

    Keeps track of the latest status update and intermediate outputs (not yet implements).
    """
    latest_status: StatusUpdate = ...
    outputs: list[Any] = ...


@dataclass
class Communicator:
    """Helper class to help communicate between the worker thread and main thread."""
    lock: Lock
    job: JobStatus
    prediction_processor: Callable[..., tuple]
    reset_url: str
    should_cancel: bool = ...
    event_id: str | None = ...
    thread_complete: bool = ...
    request_headers: dict[str, str] | None = ...
    updates: asyncio.Queue[Update] = ...


def is_http_url_like(possible_url) -> bool:
    """
    Check if the given value is a string that looks like an HTTP(S) URL.
    """
    ...

def probe_url(possible_url: str) -> bool:
    """
    Probe the given URL to see if it responds with a 200 status code (to HEAD, then to GET).
    """
    ...

def is_valid_url(possible_url: str) -> bool:
    """
    Check if the given string is a valid URL.
    """
    ...

def get_pred_from_sse_v0(client: httpx.Client, data: dict, hash_data: dict, helper: Communicator, sse_url: str, sse_data_url: str, headers: dict[str, str], cookies: dict[str, str] | None, ssl_verify: bool, executor: concurrent.futures.ThreadPoolExecutor) -> dict[str, Any] | None:
    ...

def get_pred_from_sse_v1plus(helper: Communicator, headers: dict[str, str], cookies: dict[str, str] | None, pending_messages_per_event: dict[str, list[Message | None]], event_id: str, protocol: Literal["sse_v1", "sse_v2", "sse_v2.1"], ssl_verify: bool, executor: concurrent.futures.ThreadPoolExecutor) -> dict[str, Any] | None:
    ...

def check_for_cancel(helper: Communicator, headers: dict[str, str], cookies: dict[str, str] | None, ssl_verify: bool):
    ...

def stream_sse_v0(client: httpx.Client, data: dict, hash_data: dict, helper: Communicator, sse_url: str, sse_data_url: str, headers: dict[str, str], cookies: dict[str, str] | None) -> dict[str, Any]:
    ...

def stream_sse_v1plus(helper: Communicator, pending_messages_per_event: dict[str, list[Message | None]], event_id: str, protocol: Literal["sse_v1", "sse_v2", "sse_v2.1", "sse_v3"]) -> dict[str, Any]:
    ...

def apply_diff(obj, diff):
    ...

def create_tmp_copy_of_file(file_path: str, dir: str | None = ...) -> str:
    ...

def download_tmp_copy_of_file(url_path: str, token: str | None = ..., dir: str | None = ...) -> str:
    """Kept for backwards compatibility for 3.x spaces."""
    ...

def get_mimetype(filename: str) -> str | None:
    ...

def get_extension(encoding: str) -> str | None:
    ...

def is_valid_file(file_path: str, file_types: list[str]) -> bool:
    ...

def encode_file_to_base64(f: str | Path): # -> str:
    ...

def encode_url_to_base64(url: str): # -> str:
    ...

def encode_url_or_file_to_base64(path: str | Path): # -> str:
    ...

def download_byte_stream(url: str, token=...): # -> Generator[bytes | bytearray, Any, None]:
    ...

def decode_base64_to_binary(encoding: str) -> tuple[bytes, str | None]:
    ...

def strip_invalid_filename_characters(filename: str, max_bytes: int = ...) -> str:
    """
    Strips invalid characters from a filename and ensures it does not exceed the maximum byte length
    Invalid characters are any characters that are not alphanumeric or one of the following: . _ - ,
    The filename may include an extension (in which case it is preserved exactly as is), or could be just a name without an extension.
    """
    ...

def sanitize_parameter_names(original_name: str) -> str:
    """Cleans up a Python parameter name to make the API info more readable."""
    ...

def decode_base64_to_file(encoding: str, file_path: str | None = ..., dir: str | Path | None = ..., prefix: str | None = ...): # -> _TemporaryFileWrapper[bytes]:
    ...

def dict_or_str_to_json_file(jsn: str | dict | list, dir: str | Path | None = ...): # -> _TemporaryFileWrapper[str]:
    ...

def file_to_json(file_path: str | Path) -> dict | list:
    ...

def set_space_timeout(space_id: str, token: str | None = ..., timeout_in_seconds: int = ...): # -> None:
    ...

def synchronize_async(func: Callable, *args, **kwargs) -> Any:
    """
    Runs async functions in sync scopes. Can be used in any scope.

    Example:
        if inspect.iscoroutinefunction(block_fn.fn):
            predictions = utils.synchronize_async(block_fn.fn, *processed_input)

    Args:
        func:
        *args:
        **kwargs:
    """
    ...

class APIInfoParseError(ValueError):
    ...


def get_type(schema: dict): # -> dict[Any, Any] | Literal['const', 'enum', '$ref', 'oneOf', 'anyOf', 'allOf']:
    ...

FILE_DATA_FORMATS = ...
CURRENT_FILE_DATA_FORMAT = ...
def json_schema_to_python_type(schema: Any) -> str:
    ...

def python_type_to_json_schema(type_hint: Any) -> dict:
    ...

def traverse(json_obj: Any, func: Callable, is_root: Callable[..., bool]) -> Any:
    """
    Traverse a JSON object and apply a function to each element that satisfies the is_root condition.
    """
    ...

async def async_traverse(json_obj: Any, func: Callable[..., Coroutine[Any, Any, Any]], is_root: Callable[..., bool]) -> Any:
    """
    Traverse a JSON object and apply a async function to each element that satisfies the is_root condition.
    """
    ...

def value_is_file(api_info: dict) -> bool:
    ...

def is_filepath(s) -> bool:
    """
    Check if the given value is a valid str or Path filepath on the local filesystem, e.g. "path/to/file".
    """
    ...

def is_file_obj(d) -> bool:
    """
    Check if the given value is a valid FileData object dictionary in versions of Gradio<=4.20, e.g.
    {
        "path": "path/to/file",
    }
    """
    ...

def is_file_obj_with_meta(d) -> bool:
    """
    Check if the given value is a valid FileData object dictionary in newer versions of Gradio
    where the file objects include a specific "meta" key, e.g.
    {
        "path": "path/to/file",
        "meta": {"_type: "gradio.FileData"}
    }
    """
    ...

def is_file_obj_with_url(d) -> bool:
    """
    Check if the given value is a valid FileData object dictionary in newer versions of Gradio
    where the file objects include a specific "meta" key, and ALSO include a "url" key, e.g.
    {
        "path": "path/to/file",
        "url": "/file=path/to/file",
        "meta": {"_type: "gradio.FileData"}
    }
    """
    ...

SKIP_COMPONENTS = ...
def handle_file(filepath_or_url: str | Path): # -> dict[str, str | dict[str, str]]:
    ...

def file(filepath_or_url: str | Path): # -> dict[str, str | dict[str, str]]:
    ...

def construct_args(parameters_info: list[ParameterInfo] | None, args: tuple, kwargs: dict) -> list:
    class _Keywords(Enum):
        ...
    
    

def extract_validation_message(req: httpx.Response) -> str | None:
    """
    If the request is a 422 error and the detail contains a validation error message, return the message. Otherwise, return None.
    """
    ...

