"""Utilities for the Insanely Fast Whisper API."""

from insanely_fast_whisper_api.utils.constants import (
    API_DESCRIPTION,
    API_TITLE,
    API_VERSION,
    AUDIO_CHUNK_DURATION,
    AUDIO_CHUNK_MIN_DURATION,
    AUDIO_CHUNK_OVERLAP,
    COMMAND_TIMEOUT_SECONDS,
    CONFIG_DIR,
    DEFAULT_BATCH_SIZE,
    DEFAULT_BETTER_TRANSFORMER,
    DEFAULT_CHUNK_LENGTH,
    DEFAULT_DEVICE,
    DEFAULT_DIARIZATION_MODEL,
    DEFAULT_DTYPE,
    DEFAULT_LANGUAGE,
    DEFAULT_MODEL,
    DEFAULT_RESPONSE_FORMAT,
    DEFAULT_TIMESTAMP_TYPE,
    DEFAULT_TRANSCRIPTS_DIR,
    ENV_FILE,
    HF_TOKEN,
    MAX_AUDIO_SIZE_MB,
    MAX_BATCH_SIZE,
    MAX_CONCURRENT_REQUESTS,
    MAX_SPEAKERS,
    MIN_BATCH_SIZE,
    MIN_SPEAKERS,
    RESPONSE_FORMAT_JSON,
    RESPONSE_FORMAT_TEXT,
    SUPPORTED_AUDIO_FORMATS,
    SUPPORTED_RESPONSE_FORMATS,
    TEMP_FILE_TTL_SECONDS,
    UPLOAD_DIR,
)
from insanely_fast_whisper_api.utils.download_hf_model import (
    download_model_if_needed,
    # main as download_hf_model_main, # Potentially avoid exporting CLI main
)
from insanely_fast_whisper_api.utils.file_utils import (
    FileHandler,
    cleanup_temp_files,
    save_upload_file,
    validate_audio_file,
)

__all__ = [
    # constants
    "API_TITLE",
    "API_DESCRIPTION",
    "API_VERSION",
    "DEFAULT_MODEL",
    "DEFAULT_DEVICE",
    "DEFAULT_BATCH_SIZE",
    "DEFAULT_TIMESTAMP_TYPE",
    "DEFAULT_LANGUAGE",
    "DEFAULT_DTYPE",
    "DEFAULT_BETTER_TRANSFORMER",
    "DEFAULT_CHUNK_LENGTH",
    "MAX_BATCH_SIZE",
    "MIN_BATCH_SIZE",
    "COMMAND_TIMEOUT_SECONDS",
    "MAX_AUDIO_SIZE_MB",
    "MAX_CONCURRENT_REQUESTS",
    "DEFAULT_DIARIZATION_MODEL",
    "HF_TOKEN",
    "MIN_SPEAKERS",
    "MAX_SPEAKERS",
    "UPLOAD_DIR",
    "TEMP_FILE_TTL_SECONDS",
    "DEFAULT_TRANSCRIPTS_DIR",
    "AUDIO_CHUNK_DURATION",
    "AUDIO_CHUNK_OVERLAP",
    "AUDIO_CHUNK_MIN_DURATION",
    "DEFAULT_RESPONSE_FORMAT",
    "RESPONSE_FORMAT_JSON",
    "RESPONSE_FORMAT_TEXT",
    "SUPPORTED_RESPONSE_FORMATS",
    "SUPPORTED_AUDIO_FORMATS",
    "CONFIG_DIR",
    "ENV_FILE",
    # download_hf_model
    "download_model_if_needed",
    # "download_hf_model_main",
    # file_utils
    "validate_audio_file",
    "save_upload_file",
    "cleanup_temp_files",
    "FileHandler",
]
